### PR TITLE
Jacob

### PR DESCRIPTION
**Pull request by jacobpennington**
Added download script for demo data.

### CODE REVIEW

**Review by bburan — CHANGES_REQUESTED** [review]
This looks great, but I would use argparse. See `scripts/fit_model.py` for an example. I think it's pretty straightforward (off the top of my head so maybe a few typos):

import argparse
parser = argparse.ArgumentParser('Download demo data')
parser.add_option('destination', type=str)
parser.add_option('--unpack', action='store_true')
args = parser.parse_args()
get_demo_recordings(args.destination, args.unpack)

**Comment by jacobpennington** [comment]
Ah okay - I had used exactly that but wasn't sure how to do the optional argument for unpack. I'll add that shortly. Just had to move work machines again because my keyboard decided to stop working.

**Comment by bburan** [comment]
This looks great. However, I have mixed feelings about the default directory. I'm thinking that we should not specify a default (it can default to wherever we execute the script). The reason why I suggest this is because we are making several assumptions:

1) The user has cloned the repository to somewhere in their home folder (or other userspace). Eventually we may want to package up NEMS such that it would be installed into the hidden Python package folders (e.g., `site-packages`) that are not really meant for end-user viewing. In that case, it's not really a good idea to save the sample data to that folder.

2) We can't make assumptions about the current working directory. If I run python scripts/download_demo_data.py, then it will not be able to find the right folder for the recordings since it assumes we're invoking the script from the same folder as the script itself.

I also feel like if we're using a command-line script, we should let the user handle making folders and permissions since they should also be semi-comfortable with the command line.

What do you think? I pushed a commit to your branch that makes the suggested change.

**Comment by jacobpennington** [comment]
@bburan Ok yeah, that makes sense. Looks good to me now. I'm headed out for today but I'll be in the lab all day tomorrow. Thanks again for the help!

**Review by bburan — APPROVED** [review]

**Pull request merged**
