### PR TITLE
Stp

### PR DESCRIPTION
**Pull request by svdavid**
Mostly fitting & plotting support for STP. STP works but is running quite slow. And the fitting could use some work.

### CODE REVIEW

**Review by jacobpennington — CHANGES_REQUESTED** [review]
Looks like merge is removing the changes made to json encoder/decoder. Was this intentional?

**Comment by bburan** [comment]
Also, this seems to have commented-out code. I thought the whole point of using git was that we didn't have to comment out code? If we ever need to revert to an older version, it's very simple with git. It would be cleaner to just delete old code rather than comment it out or rename the function.

**Comment by svdavid** [comment]
@jacobpennington No, I deleted some deprecated code from the old saving system but the new one looks like it's in place.
@buran I uncommented the b64 uri code. I don't want to delete it since we may want to use it in the future.

**Comment by jacobpennington** [comment]
Ah my mistake, read it wrong - just wanted to double check since you mentioned you some past merges had removed updates you made.

**Review by jacobpennington — APPROVED** [review]

**Pull request merged**
