### PR TITLE
Crh

### PR DESCRIPTION
**Pull request by crheller**
@svdavid this will likely break some of your scripts... feel free to reject for now. But I think we decided in the long run that data selection outside of this function is better (using select_times())

### CODE REVIEW

**Review by svdavid — CHANGES_REQUESTED** [review]
@crheller A couple questions: in the modified generate_psth_from_est_for_both_est_and_val it looks like you removed the part that takes out incorrect trials and renamed the output 'respavg_est'. Both of these will break the current psth+pupil analyses. Can you add in the function that takes care of the incorrect trial removal? Also, can we use a different name for the output signal. Maybe 'psth'?

**Comment by crheller** [comment]
@svdavid renaming to 'psth' is no problem. I removed the part that takes out incorrect trials because I assumed thats something we would want to do prior to using this function? That way you can run the jackknife on the appropriate data set. I sent you a snippet showing how I did this using the select_times function

**Review by bburan — CHANGES_REQUESTED** [review]
Can you please add unit-tests for the jackknife to make sure this bug doesn't pop-up in the future?

**Comment by bburan** [comment]
In general, it's best for a bug fix to be in it's own pull request rather than putting a whole bunch of unrelated commits in a pull request. However, no one (except me) is really doing this.

**Comment by crheller** [comment]
@bburan working on the unit test right now... was moving machines so I did it in a separate commit, sorry

**Comment by svdavid** [comment]
PSTH+state analysis seems to be working fine now. I cleaned up a couple things in the plots. 

one concern, this line in `preprocessing.generate_psth_from_est_for_both_est_and_val' runs extremely slowly now:
```folded_matrices = resp_est.extract_epochs(epochs_to_extract)```

**Comment by crheller** [comment]
@svdavid I noticed that but wasn't sure if that was the case beforehand or not so I didn't do anything with it. Maybe we can close this PR since all seems to be working, and I can try to figure out why it's so slow?

**Review by svdavid — APPROVED** [review]
Looks good. Let's leave the slow performance of `get_epoch_indices` for large segment lists as something to fix in the future.

**Comment by crheller** [comment]
@bburan I updated the unit test. Sorry again for the string of commits on this PR.

**Review by bburan — APPROVED** [review]

**Comment by bburan** [comment]
@crheller I approved this, but in the future, let's avoid convoluted lines like this:

`assert(sum(~np.isnan(jack1.as_continuous().flatten()))/jack1.as_continuous().size ==0.9) `

It should be broken down into at least three lines.

**Pull request merged**
