### PR TITLE
Normalization

### PR DESCRIPTION
**Pull request by svdavid**
Just identified a bug in the NMSE calculation that was causing overfits for cells with low firing rates. I've also started implementing a scheme for (optionally) normalizing the output of modules. Still trying to figure out how to get it working but it doesn't appear to conflict with any code.

### CODE REVIEW

**Comment by bburan** [comment]
@svdavid I don't understand why `DEBUGMODE` and `VALDATA` are required. You're creating a global variable, which is almost always considered the wrong thing to do in Python. Can you elucidate on what they accomplish? I may be able to suggest a different approach.

**Comment by svdavid** [comment]
I wanted a simple way to ask the fitter to plot something about predictions on the validation in the middle of a fit to the estimation data. So the global variables need to be accessible in the cost function so that it knows whether to generate the plot and what data to use to generate it. I figured what I did was a total hack. Yes, would be great to learn the pythonic way, though probably I'll take this out after I'm convinced that the fit is working ok.

**Comment by bburan** [comment]
In those cases what I usually do is add a `debug` parameter to the
function. Can you pass this to the fitter directly? Or, you can create a
special callback to do what debugging you need:

```
def fitter(..., debug_callback=None):
    # code here for fitting ...
    if debug_callback is not None:
        debug_callback(locals())
    # code here for fitting...

def svd_debug_callback(valdata, *kwargs):
    # do what you need to do

from functools import partial
cb = partial(svd_debug_callback, valdata)

fitter(..., debug_callback=cb)
```

**Comment by svdavid** [comment]
Ok, deleted the debugging code. I'll do something tidier if it ever is useful.

**Pull request merged**
