### PR TITLE
Revert "Firbank"

### PR DESCRIPTION
**Pull request by svdavid**
Reverts LBHB/NEMS#91

Sorry, accidentally merged in an attempt to test out the branch. Found some incompatibility with my previous use of firbank. Will test further now.

### CODE REVIEW

**Comment by svdavid** [comment]
@christianbrodbeck Sorry if I'm messing things up. I was having trouble pulling down your branch so I merged and then realized there's a difference in how I implemented firbank and how you are using it.  I was using signalmod.rep_channels to replicate the channels coming into the filterbank as a separate module.  So that if I have a two-channel stimulus and want a two filter-firbank, I should replicate the input stim to be 4 channels and then feed that to firbank.  It sounds weird but the idea is that the firbank can be generic (eg, each filter operating on a different input stimulus).
Does this make sense as a different implementation?  Not a big problem, but maybe there are two different types of firbank?  --one where each fir filter operates on an identical stimulus and one where the stimuli can be different for each filter?

**Comment by svdavid** [comment]
btw, this merge doesn't break anything except for a few models I've been testing!

**Comment by christianbrodbeck** [comment]
I see, I realize I missed the documentation on `filter_bank()`, sorry. 

Replicating the stimuli might get inefficient when using may signals (like 100s of sensors). But I'm also wondering whether what I'm trying is the right approach. Estimation time is very long, and I suspect that is because the fitter does not know that the different output channels are independent (i.e. the filters for each output channel can be estimated independently); might there be a way to specify that, or would it be better to fit 157 simple models for 157 sensors?

**Comment by svdavid** [comment]
Your implementation makes perfect sense for your use case. I just need to
make either an extra switch or a separate module to work for mine.

Will do that as soon as I can figure out how to check out your branch!

**Comment by christianbrodbeck** [comment]
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by christianbrodbeck** [comment]
Could `per_channel()` be modified to allow `n_coefficients` as well as `n_coefficients / bank_count` inputs? That seems like a simple solution that would satisfy both use cases without adding ambiguity.

**Comment by svdavid** [comment]
Testing that right now. Looks pretty straightforward... Though my current
solution could probably be made more beautiful. Stay tuned!

**Comment by svdavid** [comment]
Replacing this fix with #93

**Pull request closed without merging**
