### PR TITLE
Better version of epoch averaging

### PR DESCRIPTION
**Pull request by bburan**
This uses a simpler, more Pythonic algorithm for creating the averaged
recording, fixes a few bugs (mainly with mutability of objects) and
preserves any "sub-epochs" (i.e., epochs contained within the epochs
being averaged) that are common to all the epochs.

As a bonus, includes new unit tests (we need more of these).

### CODE REVIEW

**Review by svdavid — COMMENTED** [review]
I get a syntax error on this line in preprocessing.py:
```end = common_epochs.query(f'name == "{epoch_name}"').iloc[0]['end']```
not sure what the right syntax is for the query function

**Comment by bburan** [comment]
I guess you're using Python < 3.6.  I'm using the f-string formatting that's available in 3.6. Probably should make it backwards compatible with 3.5. I'll update.


________________________________

**Comment by bburan** [comment]
Done and rebased off of master. Does this fix everything?

**Comment by svdavid** [comment]
I see, yes, I'm running 3.5, and that seems to confuse it. Now I'm getting a similar error on line 508 of epoch.py
```matches =  epochs.query(f'name == "{epoch_name}"')```

**Comment by bburan** [comment]
@svdavid Sorry, missed that. Fixed, amended last commit, rebased off of master and did a force-push.

**Comment by bburan** [comment]
@svdavid or @jacobpennington Can you please look at this and approve or not? Thanks.

**Review by svdavid — APPROVED** [review]

**Pull request merged**
